### ISSUE TITLE
Initial Index Prop

### ISSUE THREAD

**Issue by zek** [zehfernandes/react-native-3dcube-navigation#11]
Is it possible to add a prop to set initial value?

For example I got 10 screens. But I want to start from 4th index.

**Comment by zehfernandes** [comment]
Hi @zek 

You can use the `scrollTo` method to start the page in the 4th index.

```
componentDidMount() { 
    this.cube.scrollTo(4, false)
}

render() {
return (
    <CubeNavigationHorizontal ref={view => { this.cube = view; }}>
    ...
    </CubeNavigationHorizontal>
)
```

**Comment by zek** [comment]
I am already using it as you show. But still I believe a prop would be nice.

Also as I notice callBackAfterSwipe doesn't return index instead goTo which is equivalent to position of view according to width. Is this what we really want? 

Right now I am calculating index with this code. I will send a PR for it. What do you think?
~~~
-1 * goTo / width
~~~
