### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by zek** [zehfernandes/react-native-3dcube-navigation#13]
Is it possible to implement a lazy loading feature? Right now I am using your library for story viewing as instagram does.

Some people has video stories so that would be a problem if 50+ users has video stories.

What do you think about it? Maybe even we could have something like removeClippedSubviews.

**Comment by zehfernandes** [comment]
Hmmm. That's make a lot of sense.
Maybe a method to add a new view without re-render the entire component. 🤔

**Comment by zek** [comment]
Actually I got no idea how to implement it I am not an expert on react native :/

**Comment by zek** [comment]
I inspected a bit https://github.com/archriss/react-native-snap-carousel
They use flatlist. Can we also implement flatlist?
