### ISSUE TITLE
not working on android

### ISSUE THREAD

**Issue by avishayhajbi** [zehfernandes/react-native-3dcube-navigation#2]
i'm using 
"react": "16.0.0",
"react-native": "^0.50.1",
and i did not see anything on screen.

ios works fine

**Comment by Angelk90** [comment]
@avishayhajbi , @zehfernandes : I tried on android it seems not to work.

**Comment by zehfernandes** [comment]
cool. Thanks to report 

I will try to fix this.

**Comment by 858686804268** [comment]
ios working fine.
Not working for android. Any update??

**Comment by zehfernandes** [comment]
Hi @Angelk90, I fixed the next page bug.

I will investigate this weird button effect. 🤔
